# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50a90cc21e8aac35d534813d56ca970d121021180a4318554bd2618ccc551752b5fb00d61450a38a2952988b8cf0876564cecf79f6f03878afbabf9c1d76ca2a

test:
  secret_key_base: 99dbd50807e77d524e17b29660f12fc87bbf9b4fa561df20e5f47a892aaf659006b4a5d36cb420d526e83d94ae0633258c2878730117e1a282f6d1857667a569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
